# this a deployment config for the mail service
# it is used to deploy the mail service to the kubernetes cluster
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailservice
  labels:
    app: mailservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailservice
      role: mailservice
  template:
    metadata:
      labels:
        app: mailservice
        role: mailservice
    spec:
      containers:
      - name: mailservice
        image: haizza11/photos:0.1
        ports:
        - containerPort: 5060
        command: ["mail-service"]
        envFrom:
        - secretRef:
            name: photos-env