# this is a deployment for the query service
# it is used to deploy the query service to the kubernetes cluster
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryservice
  labels:
    app: queryservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: queryservice
      role: queryservice
  template:
    metadata:
      labels:
        app: queryservice
        role: queryservice
    spec:
      containers:
      - name: queryservice
        image: haizza11/photos:0.1
        ports:
        - containerPort: 3001
        command: ["query-service"]
        envFrom:
        - secretRef:
            name: photos-env