# this is a deployment config for nginx
# it is used to deploy nginx to the kubernetes cluster
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      role: nginx
  template:
    metadata:
      labels:
        app: nginx
        role: nginx
    spec:
      containers:
      - name: nginx
        image: haizza11/photos-nginx:0.3
        ports:
        - containerPort: 80