# this is a deployment config for nginx
# it is used to deploy nginx to the kubernetes cluster
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.opensource.zalan.do/zalan/nginx:latest
        ports:
        - containerPort: 80
`