version: '3'

services: 
  mailservice:
    container_name: mailservice
    build: "."
    command: "mail-service"
    ports:
      - "5060"
    env_file:
      - "./.env"

  uploadservice:
    container_name: uploadservice
    build: "."
    command: "upload-service"
    ports:
      - "5070"
    env_file:
      - "./.env"
    
  commandservice:
    container_name: commandservice
    build: "."
    command: "command-service"
    ports:
      - "3000"
    depends_on:
      - mailService
      - uploadService
    env_file:
      - "./.env"

  queryservice:
    container_name: queryservice
    build: "."
    command: "query-service"
    ports:
      - "3000"
    depends_on:
      - mailService
      - uploadService
    env_file:
      - "./.env"
  nginx:
    container_name: nginx
    build: "./nginx/"
    ports:
      - "8000:80"
    depends_on:
      - commandservice
      - queryservice
      - mailservice
      - uploadservice