# this a service definition for the upload service
# it is used to expose the upload service to other services in the kubernetes cluster
# the service kind is ClusterIP because we don't want to expose the service to the outside world
#

apiVersion: v1
kind: Service
metadata:
  name: uploadservice
  labels:
    app: uploadservice
    role: uploadservice
spec:
  type: ClusterIP
  ports:
  - port: 5070
    targetPort: 5070
  selector:
    app: uploadservice
    role: uploadservice